add "copy way {left,right,up,down}"
talonhub/community pull request #1192
Opened 2023-05-10 19:49 UTC by rntz

Adds "copy way {left,right,up,down}" commands. Also moves the scroll commands in `edit.talon` closer together and clarifies a few doc strings.

2023-05-11 06:12 UTC, AndreasArvidsson approved these changes

2023-05-13 15:54 UTC, nriley requested changes

2023-05-13 15:54 UTC, nriley commented on core/edit/edit.talon
> +
On the knausj grooming session we had agreed that it may make more sense to make these individual actions rather than compound actions.

2023-06-24 02:02 UTC, splondike approved these changes

2023-06-24 16:58 UTC, rntz commented
It's a bit confusing that `<action> way left` and `<action> line start` do different things with this PR. Eg `select`, `copy`, etc.

This follows the differences introduced in #1182, I think.

The difference is: `select line start` tries to cancel the current selection if there is one before going to head of line, while `select way left` tries to extend the current selection.

We should discuss this further.

2024-11-03 03:29 UTC, knausj85 commented
At this point, I think this is probably best reimplemented via the compound edit commands implemented in https://github.com/talonhub/community/pull/1498. Closing this one out.

2024-11-03 03:29 UTC, closed without merging