Added voice command to create Talon application context
talonhub/community pull request #1242
Opened 2023-08-04 13:54 UTC by AndreasArvidsson

`"talon create app context"` will generate a new folder in `apps` with a Talon and a python file. 

Example from visual studio code: 

`apps/visual_studio_code/visual_studio_code.talon`
```talon
app: visual_studio_code
-

```

`apps/visual_studio_code/visual_studio_code.py`
```py
from talon import Module, Context, actions

mod = Module()
ctx = Context()

mod.apps.visual_studio_code = r"""
os: windows
and app.exe: Code.exe
"""

ctx.matches = r"""
app: visual_studio_code
"""

# @mod.action_class
# class Actions:
```

2023-08-04 14:09 UTC, nriley commented
Would recommend you create platform-specific .py/.talon files by default (e.g., visual_studio_code_win.py/talon). Some of us use Talon on more than one platform…

2023-08-04 14:13 UTC, AndreasArvidsson commented
Is that standard for community now? When I look in the applications folder it's quite rare.

2023-08-04 14:36 UTC, nriley commented
It's a standard we discussed when we did our last rearrangement. Since keyboard commands usually differ between platforms, and my feeling is that if you're using this feature, you may not be an advanced user enough to be able to build a cross-platform implementation, so it's better for the defaults to be "safe".

2023-08-04 14:40 UTC, AndreasArvidsson commented
Sounds reasonable

2023-08-04 15:02 UTC, AndreasArvidsson commented
@nriley Better?

2023-08-04 15:12 UTC, nriley commented
I'd recommend adding the platform suffix to the .talon file and the app: as well.

Also — if you're not watching the log, it doesn't seem like anything happens when I use this command. Perhaps consider opening the directory in the user's file browser, or at the least popping up a notification?

2023-08-04 15:26 UTC, AndreasArvidsson commented
I don't think it makes sense to have a talon file per os for a single app. Maybe We can talk about this in tomorrow's meetup?

2023-08-19 16:16 UTC, AndreasArvidsson commented
@nriley In today's meetup we decided to make the platform name an optional word in the spoken phrase. The current implementation just repeats the command I would prefer to have a list(`user.platform`) instead. What do people think?

2023-09-02 15:25 UTC, nriley requested changes

2023-09-02 15:25 UTC, nriley commented on plugin/talon_helpers/create_app_context.py
> +        """Create a new python context file for the current application"""
Maybe include something about the directory here

2023-09-02 15:29 UTC, nriley approved these changes

2023-09-02 15:29 UTC, merged