Turning off listening mode after a timeout
talonhub/community pull request #1320
Opened 2023-11-24 14:09 UTC by mik-menshikov

2023-12-27 02:30 UTC, fidgetingbits requested changes
This seems like a nice idea after a quick review. 
 
One of talon strong points is it that shouldn't need to restarted almost ever, so this should avoid restart being required imo. 

To do this you could instead read the timeout from the settings from inside the called functions, rather than once at startup.

Also, you could register the post_phrase hook regardless of the timeout value, and then inside the callback check the setting value to decide if it a timeout handler should be used. The perf hit for flag check should be negligible, so I think it's OK.

2024-02-18 16:51 UTC, knausj85 commented
I really like this functionality, thanks @mik-menshikov. I made some changes after testing and experimenting with it a bit. This is ready for review again.

2024-04-06 11:39 UTC, knausj85 approved these changes

2024-04-06 11:53 UTC, knausj85 approved these changes

2024-04-06 11:53 UTC, merged