coalesce some list updates
talonhub/community pull request #1348
Opened 2024-01-03 09:15 UTC by lunixbochs

Snippets and file manager list updates trigger more context refreshes than necessary. Due to an indentation issue, snippets are currently triggering 101 full context re-evaluations every time snippets reload (linear to number of snippets).

2024-01-03 10:25 UTC, AndreasArvidsson submitted a review, later dismissed

2024-01-03 16:06 UTC, pokey requested changes
I don't think this is right. `ctx` is local to the outer `for` loop; [defined in its guard](https://github.com/talonhub/community/pull/1348/files#diff-28c99d57b6152f53ca35d94c3471b72f32d5e8bc35a6edc2b4b4ca8388ddc0bcR72)

2024-01-21 21:20 UTC, knausj85 commented
I'm inclined to merge this after fixing the indentation and open an issue to until someone has the bandwidth to address lunixboch's broader suggestion re: removing snippets setting.

This is at least an improvement in an interim.

2024-01-23 14:33 UTC, pokey commented
I don't think this is right. `ctx` is a local variable to the 

> If that's the case, I'm going to strongly recommend you remove the dir setting and use a directory relative to the code, so the contexts can be populated before Talon is ready.

We implemented this feature in response to a user request (https://github.com/talonhub/community/issues/1306), but if untenable, I guess we could roll it back?

> I'll also recommend in the fs.watch only updating the file that changed (if you're not doing that). This code path is currently triggering a lot of work inside Talon.

Makes sense; prob for a follow-up PR though. Filed https://github.com/talonhub/community/issues/1373 to track

2024-01-29 13:52 UTC, pokey approved these changes
Looks good to me! I have not tested locally, though

2024-01-30 00:12 UTC, merged