Use settings.get() in more places
talonhub/community pull request #1351
Opened 2024-01-07 22:09 UTC by brief

Builds on #1349 by converting most uses of `setting = mod.setting()` in community to `settings.get()`.

@lunixbochs, would appreciate a quick look to make sure this is correctly using settings.

2024-01-13 22:20 UTC, nriley requested changes
Thanks for doing this!

2024-01-13 22:20 UTC, nriley commented on apps/tmux/tmux.py
> +        actions.key(f"{settings.get('user.tmux_prefix_key')}")
Think this may have been generated due to .talon → .py action conversion; would just get rid of the format string.

2024-01-13 22:20 UTC, nriley commented on core/help/help_scope.py
> +        return f"{value[:settings.get('user.help_scope_max_length')]} ..."
Would just retrieve the setting once.

2024-01-13 22:20 UTC, nriley commented on core/snippets/snippets.py
> +    dir = Path(settings.get("user.snippets_dir"))
Just retrieve once.

2024-01-14 02:20 UTC, brief commented
Thanks for the review @nriley. Changes made.

The one plugin I haven't updated yet is the mode indicator, mostly because of [this part](https://github.com/talonhub/community/blob/2f7de0d36637f6b24e1be19dd793265785e280db/plugin/mode_indicator/mode_indicator.py#L49-L64).

Changing it throws skipped settings warnings, since I assume the plugin loads before the settings do. Removing it and the reference on line 182 has everything working as it should, but I'm hesitant to do that without first knowing why @AndreasArvidsson included it in the first place.

2024-01-14 03:31 UTC, nriley commented
> Changing it throws skipped settings warnings, since I assume the plugin loads before the settings do. Removing it and the reference on line 182 has everything working as it should, but I'm hesitant to do that without first knowing why @AndreasArvidsson included it in the first place.

Yeah, I wonder if that is "approved" usage; it certainly seems like a neat trick if you've got something persistent that depends on a bunch of settings.

2024-01-14 08:12 UTC, AndreasArvidsson commented
You just need to add actual strings instead
```
setting_paths = [
    "user.mode_indicator_show",
    "user.mode_indicator_size",
    ...
]
```

2024-01-14 16:19 UTC, brief commented
Makes sense. Thanks for the help. That should be everything.

2024-01-15 15:33 UTC, merged