refactor: move command_client folder into core
talonhub/community pull request #1448
Opened 2024-05-31 07:56 UTC by fidgetingbits

This is mostly just a nit, but every time I go to find `command_client/` in community I go to the wrong place, because I don't associate it with vscode. Since there's other users of it now, like neovim-talon now, it probably makes sense for this to just become part of `core/`. It could also be suited to `plugin/`, but if we ever decided to move all of the app-specific stuff (only vscode and visual_studio atm) into the associated `apps/<foo>/` folders then this would be `apps/` relying on `plugin/` which we don't want.

2024-05-31 10:42 UTC, pokey requested changes
I agree in principle, but we'll need to figure out how it interacts with the git subtree push. I'll need to do a bit of googling / experimentation to make sure it will work. See the README in this directory if you're not sure what I'm referring to

I'm going to mark this as needs changes for now just so we don't merge, and we'll also need to update the README with the new subtree push command once we figure it out

2024-05-31 10:44 UTC, pokey commented
> this would be apps/ relying on plugin/ which we don't want.

Hmm not sure bout that one. I def think core shouldn't rely on apps or plugins, but I'm not sure I see an issue with apps relying on plugins

2024-05-31 10:55 UTC, fidgetingbits commented
> > this would be apps/ relying on plugin/ which we don't want.
> 
> Hmm not sure bout that one. I def think core shouldn't rely on apps or plugins, but I'm not sure I see an issue with apps relying on plugins

Ya that makes sense actually. In that case I'd probably opt for it to go in plugin? but really I'm good with either.

2024-09-24 12:19 UTC, auscompgeek commented
It's been a while since I've used git subtree, but I don't think there's any reason why it wouldn't like a directory move.

2025-01-12 08:35 UTC, AndreasArvidsson commented
Replaced by #1678

2025-01-12 08:35 UTC, closed without merging