Fixing display of scroll mode for wheel gaze.iu~~
talonhub/community pull request #1485
Opened 2024-07-07 19:04 UTC by bradmajewski

2024-07-07 19:23 UTC, bradmajewski commented
Forced pushed due to needing to fix the author of the commit

2024-07-15 15:32 UTC, AndreasArvidsson commented on plugin/mouse/mouse.py
>          global continuous_scroll_mode
Feedback from the community meetup. The global should be the first line in the function otherwise this looks good.

2024-07-15 15:32 UTC, AndreasArvidsson requested changes
Feedback from the community meetup. The global should be the first line in the function otherwise this looks good.

2024-07-16 07:12 UTC, AndreasArvidsson approved these changes

2024-07-16 07:12 UTC, merged