Convert keys to .talon-list where possible
talonhub/community pull request #1554
Opened 2024-09-01 00:52 UTC by knausj85

- does not port punctuation_words or symbol_keys, as these are used by create spoken forms
- adds support for keypad keys

2024-09-01 00:54 UTC, knausj85 commented
We discussed the old PR (https://github.com/talonhub/community/commit/940fe694bdb1b5ea752fc2e62154a255f055734e) a bit in the backlog session. The thinking is to avoid trying to create some sort of auto-conversion mechanism and live with a manual merge for python lists we convert to *.talon-list.

2024-09-07 16:25 UTC, AndreasArvidsson commented on core/keys/function_key.talon-list
> +f thirteen: f13
We should probably comment everything above twelve

2024-09-07 16:44 UTC, AndreasArvidsson requested changes
We should probably leave a link to the wiki in letters and modifier lists

2024-09-07 16:46 UTC, nriley commented
https://talon.wiki/Quickstart/improving_recognition_accuracy#collected-alternatives-to-the-default-alphabet is for the alphabet; we should migrate our recommended modifier alternatives to the wiki too.

2024-09-07 17:59 UTC, knausj85 commented
Since the modifiers aren't already on the wiki, maybe we save that bit for another. I think this is good to go.

2024-09-07 22:40 UTC, nriley requested changes

2024-09-07 22:46 UTC, nriley commented
> Since the modifiers aren't already on the wiki, maybe we save that bit for another day. I think this is good to go.

Heh, I didn't see this before I put together a wiki change :-) Let me know if you want some other alternatives; I included the ones from the comments plus the ones I use personally.

https://github.com/TalonCommunity/Wiki/pull/302/files#diff-6eb918b959893584905f667cd9806ebf3f89362a8ecf3534138f985d80236fc2R92

2024-09-08 02:33 UTC, knausj85 commented on core/keys/keys.py
> +@mod.capture(rule="{self.keypad_key}")
Maybe we open an issue, and do a cleanup pass on this file separately from this PR? Not sure it's worth holding up the PR, and the removal of other captures is a (theoretically) breaking change.

2024-09-08 02:41 UTC, knausj85 commented
> > Since the modifiers aren't already on the wiki, maybe we save that bit for another day. I think this is good to go.
> 
> Heh, I didn't see this before I put together a wiki change :-) Let me know if you want some other alternatives; I included the ones from the comments plus the ones I use personally.
> 
> https://github.com/TalonCommunity/Wiki/pull/302/files#diff-6eb918b959893584905f667cd9806ebf3f89362a8ecf3534138f985d80236fc2R92

Those look good to me, thanks. Forgot I'm a member over on the wiki org too, and can do things 🐙

2024-09-08 02:47 UTC, nriley commented on core/keys/keys.py
> +@mod.capture(rule="{self.keypad_key}")
Sure, I'm OK either way!

2024-09-08 03:05 UTC, knausj85 commented on core/keys/keys.py
> +@mod.capture(rule="{self.keypad_key}")
https://github.com/talonhub/community/issues/1560

2024-10-05 16:38 UTC, nriley approved these changes

2024-10-05 16:39 UTC, merged

2024-10-07 17:58 UTC, nriley commented
Ugh, we missed 'insert" too...