Make numbers more consistent
talonhub/community pull request #1592
Opened 2024-11-11 10:44 UTC by AndreasArvidsson

Makes numbers more consistent between prose formatters and the global number command. 

Increase consistency and additional delimiters for different locales

Fixes #1245

2024-11-23 22:00 UTC, knausj85 requested changes
Few typos I think, otherwise I think this change makes sense

2024-11-23 22:00 UTC, knausj85 commented on core/numbers/numbers.py
> +@mod.capture(rule="<user.number_string> ((dot | point) <number_string>)+")
```suggestion
@mod.capture(rule="<user.number_string> ((dot | point) <user.number_string>)+")
```

2024-11-23 22:00 UTC, knausj85 commented on core/numbers/numbers.py
> +@mod.capture(rule="<user.number_string> (comma <number_string>)+")
```suggestion
@mod.capture(rule="<user.number_string> (comma <user.number_string>)+")
```

2024-11-23 22:00 UTC, knausj85 commented on core/numbers/numbers.py
> +@mod.capture(rule="[negative | minus] <user_number_string>")
```suggestion
@mod.capture(rule="[negative | minus] <user.number_string>")
```

2024-11-23 22:15 UTC, knausj85 commented on core/numbers/numbers.py
> +    number = m.user_number_string
```suggestion
    number = m.number_string
```

2024-11-23 22:20 UTC, knausj85 commented
There's one other inconsistency that might be worth addressing while in here, or as a separate issue: 
can't dictate negative numbers with decimals.

2024-11-24 05:12 UTC, AndreasArvidsson commented
Fixes applied.

Negative decimal numbers for something I thought about but since we have a specific signed numbers for integers do we need something similar for decimals or should we just make one capture supporting both? I think we should leave that as a separate issue.

2024-11-24 05:31 UTC, knausj85 approved these changes
looks good, thanks. I agree with handling the negative numbers in a separate issue.

2024-11-24 05:31 UTC, merged

2024-11-24 05:50 UTC, AndreasArvidsson commented
Issue filed
https://github.com/talonhub/community/issues/1615