Remove symbols from create spoken forms & migrate to *.talon-list
talonhub/community pull request #1638
Opened 2024-12-14 22:15 UTC by knausj85

https://github.com/talonhub/community/issues/1561

2024-12-14 23:23 UTC, knausj85 commented
This is ready for folks to test in order to decide whether we want to proceed with the change.

2025-01-04 17:29 UTC, knausj85 commented on core/create_spoken_forms.py
>  FANCY_REGULAR_EXPRESSION = r"[A-Z]?[a-z]+|[A-Z]+(?![a-z])|[0-9]+"
strip apostrophes, ensure everything else is a space.

2025-01-19 18:02 UTC, knausj85 commented
After our discussion, I've settled on a compromise of keeping support for a handful of symbols. Unfortunately, this does mean folks have to define them in two places. However, I feel it is a step in the right direction. 

This is ready for review.

2025-01-25 15:08 UTC, nriley requested changes

2025-01-25 15:08 UTC, nriley commented on core/keys/symbol_key.talon-list
> +R square: ]
Would recommend you capitalize R everywhere (my preference) or nowhere; right now it's inconsistent.

2025-01-25 15:08 UTC, nriley commented on core/keys/symbol_key.talon-list
> +r brace: }
We have "R" here but not "L".

2025-01-25 15:38 UTC, knausj85 commented on core/keys/symbol_key.talon-list
> +r brace: }
This variant was apparently never in keys.py. Added.

2025-01-25 15:39 UTC, knausj85 commented on core/keys/symbol_key.talon-list
> +R square: ]
Fair enough, this was auto converted and apparently inconsistent in the original. Fixed

2025-01-25 15:52 UTC, nriley reviewed
Looks good to me, but I haven't run with it yet!

2025-02-08 17:40 UTC, AndreasArvidsson commented on core/create_spoken_forms.py
> +# Keep support for a handful of symbols.
Elaborate on why we're keeping these three

2025-02-08 17:59 UTC, knausj85 commented on core/create_spoken_forms.py
> +# Keep support for a handful of symbols.
Done

2025-02-08 18:00 UTC, AndreasArvidsson approved these changes

2025-02-10 01:16 UTC, knausj85 commented
I'm having second thoughts about this one due to the response on https://github.com/talonvoice/talon/issues/680

Maybe we're better off doing something similar to the code languages stuff and defining these in a separate python file.

2025-02-10 08:15 UTC, AndreasArvidsson commented
> I'm having second thoughts about this one due to the response on [talonvoice/talon#680](https://github.com/talonvoice/talon/issues/680)
> 
> Maybe we're better off doing something similar to the code languages stuff and defining these in a separate python file.

I guess that's our best option at the moment.

2025-02-15 17:33 UTC, nriley reviewed
Based on feedback from aegis and discussion at the community backlog session, we have decided that this is not the approach we want to take going forward.

2025-02-15 17:33 UTC, closed without merging