migrate more edit commands
talonhub/community pull request #1641
Opened 2024-12-15 06:56 UTC by knausj85

2025-01-01 04:30 UTC, knausj85 commented on core/edit/edit_command_modifiers.talon-list
> +left: left
Everything works as expected, but adding left and right adds some more-or-less worthless commands to the grammar since it extends by a character. 

"cut left" "copy left" are pretty dubious.

I wonder if left / right / word left / up / down should be re-worked to be consistent with our arrows grammar e.g. copy 2 left, copy 2 up etc instead.

2025-01-04 17:22 UTC, knausj85 commented on core/edit/edit_command_modifiers.talon-list
> +left: left
Ensure this idea works with classic repeaters

2025-01-05 04:42 UTC, knausj85 commented on core/edit/edit_command_modifiers.talon-list
> +left: left
> Ensure this idea works with classic repeaters

@nriley FYI eg cut word left 3rd vs cut 3 word left will render different results for likely obvious reasons.

Since cut is destructive, only the final word would be on the clipboard with the classic repeaters, whereas cut 3 word left can be implemented to do what I would expect: three words on the clipboard. 

Copy/Selection actions work as expected with either.

2025-02-01 17:58 UTC, nriley requested changes

2025-02-01 17:58 UTC, nriley commented on core/edit/edit_command.py
> +    desc="Sleep required between word selections",
Can you explain a bit more as to why this is necessary?

2025-02-02 00:32 UTC, knausj85 commented on core/edit/edit_command.py
> +    desc="Sleep required between word selections",
Added comment above the setting.

2025-02-02 15:32 UTC, nriley commented
Working well so far. In merging it into my own repo the largest issue I ran into was that there's no consistency between navigation (`go …`) and editing (`select …`). Seems that we should consider reusing `edit_command_modifiers_repeatable` in `navigation_step` since you would typically want to use the same words in both cases. Probably best in another PR; can file as an issue if you want.

2025-02-02 15:51 UTC, nriley approved these changes

2025-02-02 17:30 UTC, knausj85 commented
I agree with consolidating those grammars; let's do a separate PR/issue for it if you don't mind.

2025-02-02 19:00 UTC, merged

2025-02-02 19:02 UTC, nriley commented
Filed #1728. Thanks!