Refactor code operators
talonhub/community pull request #1650
Opened 2024-12-22 11:50 UTC by AndreasArvidsson

Fixes #1597

I think this is where we landed in our latest discussion. Please have a look and give feedback. I would also want a community user to test drive this thoroughly.

2025-01-02 22:07 UTC, FireChickenProductivity commented
I get exceptions when I use this (using the latest beta on Mac).  I simply cannot use any of the operator commands. I tried merging the latest community changes into my local copy of the branch to see if that helped, but I still got the following exceptions:

2025-01-02 14:53:45.624 ERROR cb error topic="phrase" cb=SpeechSystem.engine_event
   16:      lib/python3.11/threading.py:1002* # cron thread
   15:      lib/python3.11/threading.py:1045* 
   14:      lib/python3.11/threading.py:982 * 
   13:                    talon/cron.py:159 | 
   12:                     talon/vad.py:23  | 
   11:                     talon/vad.py:129 | 
   10: talon/scripting/speech_system.py:396 | 
    9:             talon/engines/w2l.py:743 | 
    8:      talon/scripting/dispatch.py:134 | # 'phrase' main:EngineProxy._redispatch()
    7: talon/scripting/speech_system.py:69  | 
    6: -------------------------------------# [stack splice]
    5:      talon/scripting/dispatch.py:134 | # 'phrase' main:SpeechSystem.engine_event()
    4: talon/scripting/speech_system.py:518 | 
    3:      talon/scripting/executor.py:112 | 
    2:  talon/scripting/talon_script.py:823 | 
    1:  talon/scripting/talon_script.py:725 | 
talon.scripting.talon_script.TalonScriptError: 
 in script at /Users/name/.talon/user/knausj_talon/lang/tags/operators.talon:5:
 > user.code_operator(code_operators_math)
NotImplementedError: Action 'user.code_get_operators' exists but the Module method is empty and no Context reimplements it


When coding in java, I instead get the following

2025-01-02 14:58:37.865 ERROR     7:          talon/scripting/talon_script.py:721| 
    6:          talon/scripting/talon_script.py:314| 
    5:               talon/scripting/actions.py:88 | 
    4: user/knausj_talon/lang/tags/operators.py:88 | operators: Operators = actions.user.co..
    3:                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    2:               talon/scripting/actions.py:69 | 
    1:                 talon/scripting/types.py:155| 
TypeError: Function 'user.code_get_operators' incompatible with prototype 'user.code_get_operators'
  Signature: () -> user.knausj_talon.lang.tags.operators.Operators
  Expected:  () -> Optional[user.knausj_talon.lang.tags.operators.Operators]
  - Return type mismatch. Found 'user.knausj_talon.lang.tags.operators.Operators', expected 'Optional[user.knausj_talon.lang.tags.operators.Operators]' (or no annotation)

[The below error was raised while handling the above exception(s)]
2025-01-02 14:58:37.868 ERROR cb error topic="phrase" cb=SpeechSystem.engine_event
   16:      lib/python3.11/threading.py:1002* # cron thread
   15:      lib/python3.11/threading.py:1045* 
   14:      lib/python3.11/threading.py:982 * 
   13:                    talon/cron.py:159 | 
   12:                     talon/vad.py:23  | 
   11:                     talon/vad.py:129 | 
   10: talon/scripting/speech_system.py:396 | 
    9:             talon/engines/w2l.py:743 | 
    8:      talon/scripting/dispatch.py:134 | # 'phrase' main:EngineProxy._redispatch()
    7: talon/scripting/speech_system.py:69  | 
    6: -------------------------------------# [stack splice]
    5:      talon/scripting/dispatch.py:134 | # 'phrase' main:SpeechSystem.engine_event()
    4: talon/scripting/speech_system.py:518 | 
    3:      talon/scripting/executor.py:112 | 
    2:  talon/scripting/talon_script.py:823 | 
    1:  talon/scripting/talon_script.py:725 | 
talon.scripting.talon_script.TalonScriptError: 
 in script at /Users/name/.talon/user/knausj_talon/lang/tags/operators.talon:2:
 > user.code_operator(code_operators_assignment)
TypeError: Function 'user.code_get_operators' incompatible with prototype 'user.code_get_operators'
  Signature: () -> user.knausj_talon.lang.tags.operators.Operators
  Expected:  () -> Optional[user.knausj_talon.lang.tags.operators.Operators]
  - Return type mismatch. Found 'user.knausj_talon.lang.tags.operators.Operators', expected 'Optional[user.knausj_talon.lang.tags.operators.Operators]' (or no annotation)

2025-01-02 22:14 UTC, AndreasArvidsson commented
Talon is a little bit finicky about context return types. Please try now.

2025-01-02 23:18 UTC, FireChickenProductivity commented
"op plus" worked for java but not python.

2025-01-02 16:11:32.931 ERROR cb error topic="phrase" cb=SpeechSystem.engine_event
   16:      lib/python3.11/threading.py:1002* # cron thread
   15:      lib/python3.11/threading.py:1045* 
   14:      lib/python3.11/threading.py:982 * 
   13:                    talon/cron.py:159 | 
   12:                     talon/vad.py:23  | 
   11:                     talon/vad.py:129 | 
   10: talon/scripting/speech_system.py:396 | 
    9:             talon/engines/w2l.py:743 | 
    8:      talon/scripting/dispatch.py:134 | # 'phrase' main:EngineProxy._redispatch()
    7: talon/scripting/speech_system.py:69  | 
    6: -------------------------------------# [stack splice]
    5:      talon/scripting/dispatch.py:134 | # 'phrase' main:SpeechSystem.engine_event()
    4: talon/scripting/speech_system.py:518 | 
    3:      talon/scripting/executor.py:112 | 
    2:  talon/scripting/talon_script.py:823 | 
    1:  talon/scripting/talon_script.py:725 | 
talon.scripting.talon_script.TalonScriptError: 
 in script at /Users/name/.talon/user/knausj_talon/lang/tags/operators.talon:5:
 > user.code_operator(code_operators_math)
NotImplementedError: Action 'user.code_get_operators' exists but the Module method is empty and no Context reimplements it


 I got it to work locally by replacing the default definition with the following and then checking for 7 instead of none. It seems that having an action that only returns none causes problems.

def code_get_operators() -> Optional[Operators]:
        """Get code operators dictionary"""
        return 7

 I could also get away with the following:

def code_get_operators() -> Optional[Operators]:
        """Get code operators dictionary"""
        if 'chicken':
            return None

2025-01-03 07:03 UTC, AndreasArvidsson commented
Yeah I forgot that Talon interprets `return None` as an action not being implemented. I think I have a fix for this now using a try catch instead.

2025-01-12 21:15 UTC, knausj85 commented on lang/tags/operators.py
> +        operators: Operators = actions.user.code_get_operators()
The fallback mechanism might work better without this line ;)

2025-01-12 21:39 UTC, AndreasArvidsson commented on lang/tags/operators.py
> +        operators: Operators = actions.user.code_get_operators()
Very true :D
Fixed now

2025-01-12 22:01 UTC, knausj85 commented on lang/tags/operators.py
> +        case "subscript":
```suggestion
        case "SUBSCRIPT":
```

2025-01-12 22:24 UTC, knausj85 commented
This is working well on my end. I'll put it through a few more paces this week, but I think we're probably good to go. Very clean!

I think we just need to decide what to do about all the variants that have been removed. Maybe we create a _deprecated.talon file for each. Or we just live with it

2025-01-13 10:48 UTC, AndreasArvidsson commented
Thank you for testing!

I guess we can have a discussion about that on Saturday? That gives you almost a week to thoroughly test it as well.

2025-01-18 17:23 UTC, nriley commented
On the community backlog session we were worried about breaking existing code and decided to add deprecated implementations of the existing actions that will display a message and be implemented in terms of their replacements.

2025-01-19 07:19 UTC, AndreasArvidsson commented
Okay the old commands are re added and deprecated. In some cases there are weird overlaps with a lot of optionals, but I did my best.

2025-01-19 16:40 UTC, nriley commented
Thanks. I hadn't registered that this would result in a major change to the available operator voice commands as well as the actions, and had assumed you'd implement deprecation at the level of the actions rather than the voice commands. Use of the removed actions in your own code will result in an error, which I guess is OK! I would recommend adding something to `BREAKING_CHANGES.txt` though (wonder if this would be better as a `BREAKING_CHANGES.md`...)

How do others feel about the canonicalization of voice commands such that each operator voice command starts with `op` and there is only one way of saying each operator? These changes also make it clearer where to customize the commands, but could also increase misrecognitions, e.g. between `op and` and `op in`.

Note that I'm not saying to keep all the old ways! Some obviously need replacement, e.g. `(op | logical | bitwise) (ex | exclusive) or equals:` makes no sense.

I'll try running with this for a week, but if others who voice code more than I do could provide feedback, it'd be helpful before we ask all the users of community to start retraining themselves!

2025-01-19 17:00 UTC, AndreasArvidsson commented
Please do and we can have a discussion about it next week :)

2025-01-19 17:20 UTC, nriley commented
Looking at this more carefully I see you only migrated the Java language mode and *kept* the actions because they're still used by the duplicate language modes. So we should have some way (ticket?) of keeping track of which language modes still use the individual actions, then we can actually do what I originally thought this PR did in deprecating/removing the actions.

2025-01-19 17:22 UTC, nriley requested changes

2025-01-19 17:22 UTC, nriley commented on lang/tags/operators.py
> +    def code_operator(id: str):
`id` is a Python builtin function so would recommend against using it as a parameter. (Surprised nothing warned about this!)

2025-01-19 17:32 UTC, AndreasArvidsson commented on lang/tags/operators.py
> +    def code_operator(id: str):
Oh that ship has thoroughly sailed already :D
https://search.talonvoice.com/search/?q=file%3A%5C.py%24%20%5C(id%3A%20&fold_case=auto&regex=true&context=true

2025-01-19 17:33 UTC, AndreasArvidsson commented
> Looking at this more carefully I see you only migrated the Java language mode and _kept_ the actions because they're still used by the duplicate language modes. So we should have some way (ticket?) of keeping track of which language modes still use the individual actions, then we can actually do what I originally thought this PR did in deprecating/removing the actions.

An issue with checkboxes work maybe?

2025-01-24 14:42 UTC, auscompgeek commented on lang/tags/operators.py
> +class Operators(TypedDict):
Instead of annotating literally every key as `NotRequired`, can we make it the default here instead?
```suggestion
class Operators(TypedDict, total=False):
```

2025-01-24 14:45 UTC, AndreasArvidsson commented on lang/tags/operators.py
> +class Operators(TypedDict):
Thank you!

2025-01-25 18:05 UTC, nriley approved these changes

2025-01-25 18:05 UTC, merged